export const en = {
  app: {
    name: 'AI Council',
    tagline: 'Multi-model AI collaboration platform',
  },
  chat: {
    welcome: 'Send a message to start a relay conversation',
    generating: 'generating...',
    thinking: 'thinking...',
    error: 'An error occurred',
  },
  input: {
    placeholder: 'Type a message...',
    placeholderNoModels: 'Configure models in settings first...',
    clearConversation: 'Clear conversation',
    stopRelay: 'Stop relay',
    sendMessage: 'Send message',
  },
  sidebar: {
    newChat: 'New Chat',
    noConversations: 'No conversations yet',
  },
  status: {
    models: '{count} models',
    round: 'Round {round}/{maxRounds} · {modelName}',
    error: 'Error',
    idle: 'Idle',
  },
  settings: {
    title: 'Model Settings',
    maxRounds: 'Max Rounds',
    exportFormat: 'Export Format',
    instruction:
      'Add models below. Drag to reorder — models respond in this order. Click a model to edit its config.',
    addModel: 'Add Model',
    addModelTitle: 'Add a New Model',
    provider: 'Provider',
    apiKey: 'API Key',
    endpointUrl: 'Endpoint URL',
    quickAdd: 'Quick Add',
    modelId: 'Model ID',
    displayName: 'Display Name (optional)',
    displayNamePlaceholder: 'Custom name shown in chat',
    cancel: 'Cancel',
    preset: 'Preset',
    presetInfo: 'Preset models are provided by the server; API Key is configured by the admin.',
    noModels: 'No models added yet. Add one above.',
  },
  export: {
    exportReport: 'Export Report {filename}.{format}',
    generating: 'Generating...',
    save: 'Save {filename}',
    retry: 'Retry',
    serverError: 'Server error {status}',
    generateFailed: 'Generation failed',
    shareFailed: 'Share failed',
  },
  relay: {
    complete: 'Discussion complete after {seconds}s. Here is the research report for "{topic}"',
  },
  report: {
    header: 'MEETING MINUTES',
    subheader: 'AI Council · Multi-model Collaboration Platform',
    footer: 'Generated by AI Council',
  },
  prompts: {
    userRole: 'User',
    participantSeparator: ', ',
    dateLocale: 'en-US',
  },
};

export type Messages = typeof en;
